name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          pip install poetry bandit safety
          poetry install

      - name: Run Safety security scan
        run: |
          safety check --full-report --policy-file .safety-policy.yml

      - name: Run Bandit security scan
        run: |
          bandit -r src
